apiVersion: v1
kind: ConfigMap
metadata:
  name: ragapp-config
  namespace: sample-app-namespace-1752988212273
  labels:
    app.kubernetes.io/name: ragapp
    kubernetes.azure.com/generator: devhub
data: