apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ragapp
  labels:
    app.kubernetes.io/name: ragapp
    app.kubernetes.io/part-of: ragapp-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: ragapp