apiVersion: v1
kind: Service
metadata:
  name: ragapp
  namespace: sample-app-namespace-1752988212273
  labels:
    app.kubernetes.io/name: ragapp
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ragapp
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501